# Generated by Django 5.1.1 on 2024-09-20 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='apartmenttype',
            options={'ordering': ['property_type']},
        ),
        migrations.AlterModelOptions(
            name='cities',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='ground',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='groundtype',
            options={'ordering': ['property_type']},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='housetype',
            options={'ordering': ['property_type']},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='bit',
            new_name='min_bid',
        ),
        migrations.RemoveField(
            model_name='property',
            name='min_bit',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apartments', to='viewer.apartmenttype'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.property'),
        ),
        migrations.AlterField(
            model_name='ground',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grounds', to='viewer.groundtype'),
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='garden_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='plot_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houses', to='viewer.housetype'),
        ),
        migrations.AlterField(
            model_name='housetype',
            name='property_type',
            field=models.CharField(max_length=15),
        ),
    ]
