# Generated by Django 4.2.15 on 2024-09-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_alter_property_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property',
        ),
        migrations.AddField(
            model_name='property',
            name='property',
            field=models.ManyToManyField(to='viewer.propertytype'),
        ),
    ]
