# Generated by Django 5.1.1 on 2024-09-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_remove_property_property_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ground',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
