# Generated by Django 4.2.15 on 2024-09-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_remove_property_property_property_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property',
            new_name='holding',
        ),
    ]
