# Generated by Django 5.1.1 on 2024-09-23 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_alter_apartment_name_alter_ground_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='property',
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('estimate_value', models.IntegerField()),
                ('auction_assurance', models.IntegerField()),
                ('min_bid', models.IntegerField()),
                ('date_auction', models.DateTimeField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='viewer.cities')),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction', to='viewer.propertytype')),
            ],
            options={
                'verbose_name_plural': 'Auctions',
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.auction'),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
