# Generated by Django 5.1.1 on 2024-09-25 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_auction_options_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction',
            options={'verbose_name_plural': 'Auctions'},
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='address',
            new_name='location',
        ),
    ]
