# Generated by Django 4.2.16 on 2024-09-23 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_remove_property_holding_property_holding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='holding',
        ),
        migrations.AddField(
            model_name='property',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to='viewer.propertytype'),
        ),
    ]
