# Generated by Django 5.1.1 on 2024-09-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_auction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ground',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
