# Generated by Django 4.2.16 on 2024-09-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_remove_property_holding_property_property'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property',
            new_name='property_type',
        ),
    ]
