# Generated by Django 4.2.16 on 2024-09-24 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_alter_apartment_options_alter_apartmenttype_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('estimate_value', models.IntegerField()),
                ('auction_assurance', models.IntegerField()),
                ('min_bid', models.IntegerField()),
                ('date_auction', models.DateTimeField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='viewer.cities')),
                ('property_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction', to='viewer.propertytype')),
            ],
            options={
                'verbose_name_plural': 'Auctions',
            },
        ),
        migrations.RemoveField(
            model_name='bid',
            name='property',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.auction'),
        ),
    ]
