# Generated by Django 4.2.16 on 2024-09-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_auction_remove_bid_property_delete_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ground',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
