# Generated by Django 5.1.1 on 2024-09-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_nr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nr_id_card',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='validity_id_card',
            field=models.DateField(null=True),
        ),
    ]
